name: Trigger Rebuild

on:
  schedule:
    - cron:  '1 6 * * *'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: 'main'

    - name: Trigger GitHub Pages rebuild
      run: |
        git config user.name "Steven Goulet"
        git config user.email "steven.goulet@live.com"
        git commit --allow-empty -m "Trigger rebuild"
        git push